### ISSUE TITLE
Expose the prop function through the exports

### ISSUE THREAD

**Issue by damoclark** [poppinss/pope#2]
Hi @thetutlage ,

It would be great if you exposed the `prop` function as part of the API for this great module.  I have a use case where sometimes I need to interpolate a templated string, while other times I simply want to navigate and return only part of a data structure, in both instances using the same syntax.

So as not to break the existing API, something similar to the following could be implemented:

```javascript
module.exports = pope ;

module.exports.pope = pope ;
module.exports.prop = prop ;
```

pope and prop are assigned properties of the pope function object, and can be invoked as any of:

```javascript
var pope = require('pope') ;

pope('template',data,{options}) ; // Compatible with existing usage
pope.pope('template',data,{options}) ; // Explicit invocation of the pope function (optional)
pope.prop(data,'path') ; // Invocation of the prop function
```

In exposing the prop function, I'd also suggest that the parameters be reversed to more closely resemble the order used by pope (template/path,data,[optionally options]).

Would you consider this change for the module?

Many thanks.

Damien.

**Comment by thetutlage** [comment]
Yes, will be happy to export it

**Comment by thetutlage** [comment]
Fixed in related PR
